#include "hal_data.h"
#include "Handware/Motor.h"
#include "Handware/UART_CMD.h"
#include "Handware/PWM.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
	/* TODO: add your own code here */
	 /* ---- 用户初始化 ---- */
	    Motor_Init();       /* 初始化 4 路 PWM 和方向控制 GPIO */
	    UART_CMD_Init();    /* 初始化串口0 (SCI0, 115200 baud) — 收发 */


	    /*PWM_Init();
	    PWM_DutyCycleSet(1,0.6f);
	    PWM_DutyCycleSet(2,0.6f);
	    PWM_DutyCycleSet(3,0.6f);
	    PWM_DutyCycleSet(4,0.6f);*/


	    Motor_LeftShift(0.6f);

	    /* 发送测试消息 */
	    uint8_t test_msg[] = "UART0 TX Test — Hello from RA8P1 CPU0!\r\n";
	    UART_CMD_Send(test_msg, sizeof(test_msg) - 1);


			while(1) {
		/* 检查是否有接收数据，有则回显 */
		uint8_t rx_buf[64];
		uint32_t rx_len = UART_CMD_Recv(rx_buf, sizeof(rx_buf));
		if (rx_len > 0) {
			UART_CMD_Send(rx_buf, rx_len);  /* 回显收到的数据 */
		}
		R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
	}


	    /* 主循环：所有运动控制通过 UART 中断回调触发，此处仅保持程序运行 */
	   /*while (1) {
	        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
	    }
	/* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
	    /* Take semaphore so 2nd core can clear it */
	    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

	    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
	    /* Wait for 2nd core to start and clear semaphore */
	    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
	    {
	        ;
	    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
	    /* Signal to 1st core that 2nd core has started */
	    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
	    /* Enter non-secure code */
	    R_BSP_NonSecureEnter();
#endif
}



#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
